use PSPInterwncje

-- DIM_PRZYCZYNY
CREATE TABLE DIM_PRZYCZYNY (
  PRZYCZYNA_KEY INT PRIMARY KEY NOT NULL,
  PRZYCZYNA_OPIS NVARCHAR(200)
);

-- DIM_RODZAJ
CREATE TABLE DIM_RODZAJ (
  RODZAJ_KEY INT identity(1,1) PRIMARY KEY NOT NULL,
  RODZAJ_NAME NVARCHAR(100) NOT NULL,
  WLK NVARCHAR(50) NOT NULL,
  POZAR_LASU_PODPOWIERCHNIOWY BIT NOT NULL,
  POZAR_LASU_GLEBA BIT NOT NULL,
  POZAR_LASU_DRZEWA BIT NOT NULL,
  POZAR_LASU_POJEDYNCZE_DRZEWO BIT NOT NULL,
  SILNY_WIATR BIT NOT NULL,
  PRZYBORY_WOD BIT NOT NULL,
  OPADY_SNIEGU BIT NOT NULL,
  OPADY_DESZCZU BIT NOT NULL,
  ZAGROZENIE_CHEMICZNE BIT NOT NULL,
  ZAGROZENIE_EKOLOGICZNE BIT NOT NULL,
  ZAGROZENIE_RADIOLOGICZNE BIT NOT NULL,
  ZAGROZENIE_BUDOWLANE BIT NOT NULL,
  ZAGROZENIE_INFRASTRUKTURY_KOMUNALNEJ BIT NOT NULL,
  WYPADEK_DROGOWY BIT NOT NULL,
  WYPADEK_KOLEJOWY BIT NOT NULL,
  WYPADEK_LOTNICZY BIT NOT NULL,
  WYPADEK_NA_OBSZARZE_WODNYM BIT NOT NULL,
  ZAGROZENIE_MEDYCZNE BIT NOT NULL
);

-- DIM_KOMENDA
CREATE TABLE DIM_KOMENDA (
  KOMENDA_KEY INT identity(1,1) PRIMARY KEY NOT NULL,
  WOJEWODZTWO NVARCHAR(100) ,
  POWIAT NVARCHAR(100) ,
  GMINA NVARCHAR(100) ,
  KOD_POCZTOWY NVARCHAR(10) ,
  NAZWA_KOMENDY_WOJEWODZKIEJ NVARCHAR(400) ,
  NAZWA_KOMENDY_POWIATOWEJ NVARCHAR(400) 
);

-- DIM_WOJEWODZTWA_STAT
CREATE TABLE DIM_WOJEWODZTWA_STAT (
  WOJEWODZTWA_STAT_KEY INT identity(1,1) PRIMARY KEY NOT NULL,
  WOJEWODZTWO NVARCHAR(100) NOT NULL,
  ROK INT NOT NULL,
  RODZAJ_DANYCH NVARCHAR(200) NOT NULL,
  KATEGORIA NVARCHAR(200) NOT NULL,
  WARTOSC FLOAT NOT NULL,
  JEDNOSTKA NVARCHAR(10) NOT NULL
);

-- DIM_OBIEKTY
CREATE TABLE DIM_OBIEKTY (
  OBIEKT_KEY INT identity(1,1) PRIMARY KEY NOT NULL,
  OBIEKT_KOD_1 NVARCHAR(50) NOT NULL,
  OBIEKT_OPIS_1 NVARCHAR(400) NOT NULL,
  OBIEKT_KOD_2 NVARCHAR(50),
  OBIEKT_OPIS_2 NVARCHAR(400),
  WLASCICIEL_KOD_1 NVARCHAR(50) NOT NULL,
  WLASCICIEL_OPIS_1 NVARCHAR(400) NOT NULL,
  WOLNOSTAJACY BIT NOT NULL,
  KOMPLEKS_BUDYNKOW BIT NOT NULL,
  JEDNOKONDYGNACYJNY BIT NOT NULL,
  NISKI BIT NOT NULL,
  SREDNIOWYSOKI BIT NOT NULL,
  WYSOKI BIT NOT NULL,
  WYSOKOSCIOWY BIT NOT NULL,
  ZABYTEK BIT NOT NULL
);

-- DIM_CZAS
CREATE TABLE DIM_CZAS (
  CZAS_KEY NVARCHAR(50) PRIMARY KEY NOT NULL,
  DATE DATE NOT NULL,
  DATETIME DATETIME NOT NULL,
  HOUR TINYINT NOT NULL,
  MINUTE TINYINT NOT NULL,
  DAY_NUMBER TINYINT NOT NULL,
  DAY_SUFFIX CHAR(4) NOT NULL,
  WEEK_DAY_NUMBER TINYINT NOT NULL,
  WEEK_DAY_NAME VARCHAR(10) NOT NULL,
  WEEKEND_FLAG CHAR(3) NOT NULL,
  HOLIDAY_TEXT NVARCHAR(100) NOT NULL,
  HOLIDAY_FLAG CHAR(3) NOT NULL,
  DAY_OF_YEAR_NUMBER SMALLINT NOT NULL,
  WEEK_OF_MONTH_NUMBER TINYINT NOT NULL,
  WEEK_OF_YEAR_NUMBER TINYINT NOT NULL,
  ISO_WEEK_OF_YEAR_NUMBER TINYINT NOT NULL,
  MONTH_NUMBER TINYINT NOT NULL,
  MONTH_NAME VARCHAR(10) NOT NULL,
  QUARTER_NUMBER TINYINT NOT NULL,
  QUARTER_NAME VARCHAR(10) NOT NULL,
  YEAR_NUMBER INT NOT NULL
);

-- DIM_RODZAJ_DZIALAN
CREATE TABLE DIM_RODZAJ_DZIALAN (
  RODZAJ_DZIALAN_KEY INT identity(1,1) PRIMARY KEY NOT NULL,
  DZIALANIA_GASNICZE BIT NOT NULL,
  DZIALANIA_EWAKUACYJNE BIT NOT NULL,
  RATOWNICTWO_MEDYCZNE BIT NOT NULL,
  RATOWNICTWO_TECHNICZNE BIT NOT NULL,
  ZABEZPIECZANIE_MIEJSCA_ZDARZENIA BIT NOT NULL,
  RATOWNICTWO_CHEMICZNE BIT NOT NULL,
  USUWANIE_SKUTKOW_ZDARZENIA BIT NOT NULL,
  DZIALANIA_PORZADKOWE BIT NOT NULL,
  DZIALANIA_LOGISTYCZNE BIT NOT NULL,
  POSZUKIWANIE_OSOB_ZAGINIONYCH BIT NOT NULL,
  PRZEMIESZCZANIE_NIEBEZPIECZNYCH_ZWIERZAT BIT NOT NULL,
  ODDYMIANIE BIT NOT NULL,
  SCHLADZANIE_URZADZEN BIT NOT NULL
);

-- DIM_MIEJSCE_DZIALAN
CREATE TABLE DIM_MIEJSCE_DZIALAN (
  MIEJSCE_DZIALAN_KEY INT identity(1,1) PRIMARY KEY NOT NULL,
  WEWNATRZ_POZIOM_PIWNICY BIT NOT NULL,
  WEWNATRZ_PARTER BIT NOT NULL,
  WEWNATRZ_PIETRA_OD1_DO3 BIT NOT NULL,
  WEWNATRZ_PIETRA_OD4_DO7 BIT NOT NULL,
  WEWNATRZ_PIETRA_POWYZEJ7 BIT NOT NULL,
  DACH_PODDASZE BIT NOT NULL,
  WINDA_KOMIN_SZYB BIT NOT NULL,
  POD_WODA BIT NOT NULL,
  POD_ZIEMIA BIT NOT NULL,
  WYKOPY_OSUWISKA BIT NOT NULL,
  NA_WYSOKOSCI BIT NOT NULL
);

-- FACT_INTERWENCJE
CREATE TABLE FACT_INTERWENCJE (
  INTERWENCJE_KEY INT identity(1,1) PRIMARY KEY NOT NULL,
  ID_MELDUNEK NVARCHAR(50) NOT NULL,
  F_BEZ_JOP NVARCHAR(50) NOT NULL,
  OPERATION_TYPE NVARCHAR(100) NOT NULL,
  RODZAJ_KEY INT NOT NULL,
  KOMENDA_KEY INT,
  WOJEWODZTWO NVARCHAR(100) NOT NULL,
  POWIAT NVARCHAR(100) ,
  GMINA NVARCHAR(100) ,
  OBIEKT_KEY INT,
  DATA_ZAU_KEY NVARCHAR(50),
  DATA_LOK_KEY NVARCHAR(50),
  DATA_USU_KEY NVARCHAR(50),
  DATA_ZGL_KEY NVARCHAR(50) NOT NULL,
  DATA_DOJ_KEY NVARCHAR(50),
  DATA_POW_KEY NVARCHAR(50),
  RODZ_ZAUW NVARCHAR(300) NOT NULL,
  RODZ_ZGL NVARCHAR(300) NOT NULL,
  RODZAJ_DZIALAN_KEY INT NOT NULL,
  MIEJSCE_DZIALAN_KEY INT NOT NULL,
  WYPADKI_SMIERTELNE_RATOWNICY INT NOT NULL,
  RANNI_RATOWNICY INT NOT NULL,
  WYPADKI_SMIERTELNE_STRAZACY INT NOT NULL,
  RANNI_STRAZACY INT NOT NULL,
  WYPADKI_SMIERTELNE_INNI INT NOT NULL,
  RANNI_INNI INT NOT NULL,
  WYPADKI_SMIERTELNE_DZIECI INT NOT NULL,
  RANNI_DZIECI INT NOT NULL,
  STRATY FLOAT NOT NULL,
  STRATY_BUD FLOAT NOT NULL,
  URATOWANO FLOAT NOT NULL,
  EWAKUOWANYCH INT NOT NULL,
  HOSPITALIZOWANYCH INT NOT NULL,
  KATEGORIA_ZAGROZENIA_LUDZI NVARCHAR(100) NOT NULL,
  PRZYCZYNA_KEY INT,
  ILOSC_PRADOW_WODNYCH INT NOT NULL,
  ILOSC_PRADOW_PROSZKU INT NOT NULL,
  ILOSC_PRADOW_PIANY INT NOT NULL,
  ILOSC_PRADOW_PIANY_CIEZKIEJ INT NOT NULL,
  ILOSC_PRADOW_PIANY_SREDNIEJ INT NOT NULL,
  ILOSC_PRADOW_PIANY_LEKKIEJ INT NOT NULL,
  ZUZYCIE_WODY INT NOT NULL,
  ZUZYCIE_PROSZKU INT NOT NULL,
  ZUZYCIE_SRODKA_PIANOTWORCZEGO INT NOT NULL,
  ZUZYCIE_NEUTRALIZATOROW INT NOT NULL,
  ZUZYCIE_SORBENTOW INT NOT NULL,
  ZUZYCIE_WODY_HYDRANTY_ZEWNETRZNE INT NOT NULL,
  ZUZYCIE_WODY_ZBIORNIKI_SZTUCZNE INT NOT NULL,
  ZUZYCIE_WODY_ZBIORNIKI_NATURALNE INT NOT NULL,
  ZUZYCIE_WODY_RZEKI INT NOT NULL,
  ILOSC_LUDZI INT NOT NULL,
  ILOSC_SAMOCHODOW INT NOT NULL,
  ILOSC_SPRZETU INT NOT NULL,
  ILOSC_SAMOCHODOW_GASNICZYCH_LEKKICH INT NOT NULL,
  ILOSC_SAMOCHODOW_GASNICZYCH_SREDNICH INT NOT NULL,
  ILOSC_SAMOCHODOW_GASNICZYCH_CIEZKICH INT NOT NULL,
  ILOSC_SAMOCHODOW_GASNICZYCH_PROSZKOWYCH INT NOT NULL,
  ILOSC_SAMOCHODOW_GASNICZYCH_INNYCH INT NOT NULL,
  ILOSC_SAMOCHODOW_DRABIN INT NOT NULL,
  ILOSC_SAMOCHODOW_PODNOSNIKOW INT NOT NULL,
  ILOSC_SAMOCHODOW_SW INT NOT NULL,
  ILOSC_SAMOCHODOW_RATOWNICTWA_DROGOWEGO INT NOT NULL,
  ILOSC_SAMOCHODOW_RATOWNICTWA_TECHNICZNEGO INT NOT NULL,
  ILOSC_SAMOCHODOW_SPGAZ INT NOT NULL,
  ILOSC_SAMOCHODOW_RATOWNICTWA_WODNEGO INT NOT NULL,
  ILOSC_SAMOCHODOW_RATOWNICTWA_CHEMICZNEGO INT NOT NULL,
  ILOSC_SAMOCHODOW_OSWIETLENIA INT NOT NULL,
  ILOSC_SAMOCHODOW_LACZNOSCI INT NOT NULL,
  ILOSC_SAMOCHODOW_OPERACYJNYCH INT NOT NULL,
  ILOSC_SAMOCHODOW_RATOWNICTWA_MEDYCZNEGO INT NOT NULL,
  ILOSC_SAMOCHODOW_INNYCH_SPECJALISTYCZNYCH INT NOT NULL,
  ILOSC_SPRZETU_PLYWAJACEGO INT NOT NULL,
  ILOSC_SAMOLOTOW_SMIGLOWCOW INT NOT NULL,
  ILOSC_ZRZUTOW INT NOT NULL,
  MOTOCYKLE INT NOT NULL,
  CYSTERNY_WODNE INT NOT NULL,
  CYSTERNY_PALIWOWE INT NOT NULL,
  AUTOBUSY INT NOT NULL,
  KARETKI_POGOTOWIA INT NOT NULL,
  RADIOWOZY INT NOT NULL,
  SAMOCHODY_CIEZAROWE INT NOT NULL,
  SAMOCHODY_OSOBOWE INT NOT NULL,
  SPYCHACZE_KOPARKI INT NOT NULL,
  DZWIGI_PODNOSNIKI INT NOT NULL,
  SPRZET_PLYWAJACY INT NOT NULL,
  FOREIGN KEY (RODZAJ_KEY) REFERENCES DIM_RODZAJ(RODZAJ_KEY),
  FOREIGN KEY (KOMENDA_KEY) REFERENCES DIM_KOMENDA(KOMENDA_KEY),
  FOREIGN KEY (OBIEKT_KEY) REFERENCES DIM_OBIEKTY(OBIEKT_KEY),
  FOREIGN KEY (DATA_ZAU_KEY) REFERENCES DIM_CZAS(CZAS_KEY),
  FOREIGN KEY (DATA_LOK_KEY) REFERENCES DIM_CZAS(CZAS_KEY),
  FOREIGN KEY (DATA_USU_KEY) REFERENCES DIM_CZAS(CZAS_KEY),
  FOREIGN KEY (DATA_ZGL_KEY) REFERENCES DIM_CZAS(CZAS_KEY),
  FOREIGN KEY (DATA_DOJ_KEY) REFERENCES DIM_CZAS(CZAS_KEY),
  FOREIGN KEY (DATA_POW_KEY) REFERENCES DIM_CZAS(CZAS_KEY),
  FOREIGN KEY (RODZAJ_DZIALAN_KEY) REFERENCES DIM_RODZAJ_DZIALAN(RODZAJ_DZIALAN_KEY),
  FOREIGN KEY (MIEJSCE_DZIALAN_KEY) REFERENCES DIM_MIEJSCE_DZIALAN(MIEJSCE_DZIALAN_KEY),
  FOREIGN KEY (PRZYCZYNA_KEY) REFERENCES DIM_PRZYCZYNY(PRZYCZYNA_KEY)
);
